# Base configs
baseurl: ""
url: "https://michaelcolenso.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by M. Colenso"
subtitle: "ITAP"
author: "M. Colenso"
bio: "enthusiast"
publicise: "you're a nice lady"
web_design: "MC"
social_urls:
  facebook: "https://www.facebook.com/thatbigfluffydog"
  twitter: "https://www.twitter.com/michaelcolenso"
  instagram: "https://www.instagram.com/michaelcolenso"
  dribbble: "https://dribbble.com/michaelcolenso"
  linkedin: "https://in.linkedin.com/in/michaelcolenso"
  github: "https://www.github.com/michaelcolenso"
